services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=pet_of_the_day

  db:
    image: postgres:15
    container_name: postgres_pet_of_the_day
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pet_of_the_day
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-migrate
    depends_on:
      - db
    volumes:
      - ./database/migrations:/app/database/migrations
    entrypoint: ["/bin/bash"]
volumes:
  db_data:

