# backend/.golangci.yml
version: '2'

run:
  timeout: 5m
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - ginkgolinter
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    govet:
      enable:
        - shadow
  exclusions:
    paths:
      - "ent/*"
