FROM golang:1.24-alpine

RUN apk add --no-cache git ca-certificates bash postgresql-client

WORKDIR /app

# Installer air pour le hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]