// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Name       string  `json:"name"`
	Nickname   string  `json:"nickname"`
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	BirthDate  string  `json:"birthDate"`
	City       *string `json:"city,omitempty"`
	Country    *string `json:"country,omitempty"`
	PostalCode *string `json:"postalCode,omitempty"`
}

type User struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Nickname   string  `json:"nickname"`
	Email      string  `json:"email"`
	BirthDate  string  `json:"birthDate"`
	City       *string `json:"city,omitempty"`
	Country    *string `json:"country,omitempty"`
	PostalCode *string `json:"postalCode,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}
